steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-docker.pkg.dev/positive-nuance-460806-v3/unicode/cnn:latest',
    '.'
  ]
  id: 'CNN'

options:
 logging: CLOUD_LOGGING_ONLY

images:
- 'us-docker.pkg.dev/positive-nuance-460806-v3/unicode/cnn:latest'