steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/robotic-totem-466409-u7/cnn/cnn:latest',
    '.'
  ]
  id: 'Test Image'

options:
 logging: CLOUD_LOGGING_ONLY

images:
- 'us-central1-docker.pkg.dev/robotic-totem-466409-u7/cnn/cnn:latest'