steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'europe-west2-docker.pkg.dev/crested-return-452614-t4/test/test:latest',
    '.'
  ]
  id: 'Test Image'

options:
 logging: CLOUD_LOGGING_ONLY

images:
- 'europe-west2-docker.pkg.dev/crested-return-452614-t4/test/test:latest'